### ISSUE TITLE
عدم نمایش توکن های ارسالی به ربات برای عموم

### ISSUE THREAD

**Issue by milaadd** [ehcaning/divar-telegram-bot#11]
ممنونم بابت عرضه این ربات بسیار پر کاربرد .
من به مشکلی که برخوردم این هست که وقتی از طریق ربات پیتون پیامی برای ربات تلگرام ارسال میشود فقط مالک ربات تلگرام میتواند پیام های ارسالی از طریق ربات پیتون را ببیند و بقیه افرادی که ربات را استارت میکنن در تلگرام موفق به دیدن پیام های ارسالی نمیشود ، ایا راه حلی موجود میباشد که ربات پیتون را بعنوان ادمین ربات تلگرام معرفی کنیم که پیام های ارسالی برای همه‌ی اعضای ربات تلگرام قابل رویت باشد؟

**Comment by ehcaning** [comment]
سلام
آره، شما می‌تونید رباتتون رو به یک گروه یا کانال به عنوان ادمین اضافه کنید. با همون ربات @getidsbot هم chat_id اون گروه یا کانال رو دریافت کنید و در تنظیمات این ربات قرار بدید.
